remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@jvlk/remote-data-query on GitHub':
    - 'https://github.com/jderochervlk/remote-data-query#readme'